
# ─── ENEMIES ──────────────────────────────────────────────────────────────────
# special: None | "poison" | "drain" | "bleed" | "fear"
ENEMY_POOL = [
    # Tier 1
    {"name":"Goblin Scavenger",     "hp":14,"attack":4, "defence":1,"tier":1,"gold":(1,4),
     "loot_chance":0.6,"loot":"Relic Coin",      "death_line":"It collapses with a gurgling shriek.",                       "special":None},
    {"name":"Animated Skeleton",    "hp":18,"attack":5, "defence":3,"tier":1,"gold":(0,3),
     "loot_chance":0.5,"loot":"Iron Key",         "death_line":"The bones clatter apart. Silence returns.",                  "special":None},
    {"name":"Giant Spider",         "hp":12,"attack":5, "defence":1,"tier":1,"gold":(0,1),
     "loot_chance":0.4,"loot":"Antidote",         "death_line":"The spider curls into itself. Venom smell lingers.",         "special":"poison"},
    {"name":"Feral Hound",          "hp":16,"attack":6, "defence":2,"tier":1,"gold":(0,2),
     "loot_chance":0.3,"loot":"Bloodmoss Tincture","death_line":"The hound drops mid-lunge.",                               "special":None},
    {"name":"Goblin Archer",        "hp":10,"attack":5, "defence":1,"tier":1,"gold":(1,5),
     "loot_chance":0.4,"loot":"Health Potion",    "death_line":"The archer topples from its perch.",                        "special":None},
    {"name":"Tomb Rat Swarm",       "hp":8, "attack":4, "defence":0,"tier":1,"gold":(0,1),
     "loot_chance":0.2,"loot":"Antidote",         "death_line":"The swarm disperses into dark cracks.",                     "special":"poison"},
    {"name": "Cave Leech",
     "hp": 6, "attack": 3, "defence": 0, "tier": 1,
     "gold": (0, 2),
     "loot_chance": 0.2, "loot": "Bloodmoss Tincture",
     "death_line": "It drops from wherever it had attached. The wound it leaves is small but deliberate.",
     "special": "drain",
     "flavour": "Small, pale, wrong. They are not aggressive — they are simply hungry, "
                "and they have been hungry for a very long time."},
    {"name": "Bone Collector",
     "hp": 10, "attack": 4, "defence": 2, "tier": 1,
     "gold": (0, 3),
     "loot_chance": 0.4, "loot": "Relic Coin",
     "death_line": "The bones it had assembled collapse. They were never really attached.",
     "special": None,
     "flavour": "It builds armour from what it finds. The bones are not its own. "
                "This is somehow worse."},
    {"name": "Dust Wraith",
     "hp": 8, "attack": 5, "defence": 1, "tier": 1,
     "gold": (0, 1),
     "loot_chance": 0.3, "loot": "Antidote",
     "death_line": "Disperses. The dust that settles is a slightly different colour from the rest.",
     "special": "fear",
     "flavour": "Nearly invisible in the low light. You know it is there because the air moves wrong."},
    # Tier 2
    {"name":"Bandit",               "hp":18,"attack":6, "defence":2,"tier":2,"gold":(3,10),
     "loot_chance":0.9,"loot":"Health Potion",    "death_line":"They slump forward. Coins scatter.",                        "special":None},
    {"name":"Cave Troll",           "hp":30,"attack":8, "defence":5,"tier":2,"gold":(2,7),
     "loot_chance":0.8,"loot":"Iron Shield",      "death_line":"The troll falls like a felled tree.",                       "special":None},
    {"name":"Corrupted Sentinel",   "hp":24,"attack":7, "defence":4,"tier":2,"gold":(1,5),
     "loot_chance":0.6,"loot":"Eldrosian Spear",  "death_line":"Eldrosian markings fade from its breastplate as it stills.","special":None},
    {"name":"Wraith",               "hp":20,"attack":9, "defence":2,"tier":2,"gold":(0,4),
     "loot_chance":0.7,"loot":"Crystal Mirror",   "death_line":"It unravels into cold air, whispering something.",          "special":"drain"},
    {"name":"Ashbound Hound",       "hp":16,"attack":7, "defence":2,"tier":2,"gold":(0,2),
     "loot_chance":0.3,"loot":"Ember Flask",      "death_line":"Burns out. A scorch mark shaped like a running animal.",    "special":None},
    {"name":"Pit Crawler",          "hp":20,"attack":6, "defence":3,"tier":2,"gold":(1,4),
     "loot_chance":0.4,"loot":"Bloodmoss Tincture","death_line":"It retreats into its pit, fatally.",                       "special":"bleed"},
    {"name":"Bandit Captain",       "hp":26,"attack":8, "defence":3,"tier":2,"gold":(6,15),
     "loot_chance":0.9,"loot":"Strong Tonic",     "death_line":"The captain falls. Their crew — if any — are no longer a crew.", "special":None},
    {"name":"Shard-Seeker",          "hp":20, "attack":7,  "defence":3,  "tier":2, "gold":(8,18), "loot_chance":0.6, "loot":"Shard-Seeker's Map",
     "death_line": "The mercenary falls without ceremony. Professional to the last.", "special":None},
    {"name": "Void Hound",
     "hp": 22, "attack": 8, "defence": 2, "tier": 2,
     "gold": (2, 8),
     "loot_chance": 0.4, "loot": "Void Salt",
     "death_line": "It collapses inward. The space it occupied is briefly colder than the rest of the room.",
     "special": "bleed",
     "flavour": "Hunts by something other than smell. You cannot tell what. "
                "It always knows where you are."},
    {"name": "Corrupted Scholar",
     "hp": 18, "attack": 7, "defence": 2, "tier": 2,
     "gold": (5, 12),
     "loot_chance": 0.8, "loot": "Priest's Journal",
     "death_line": "Falls still. The book they were reading drops open. You will not look at the page.",
     "special": "drain",
     "flavour": "They came looking for answers. The answers found them first."},
    {"name": "Shard-Touched Soldier",
     "hp": 24, "attack": 9, "defence": 3, "tier": 2,
     "gold": (4, 10),
     "loot_chance": 0.5, "loot": "Fragment of the Seal",
     "death_line": "The Godshard fragment in their chest dims and goes dark. "
                   "It was keeping them upright.",
     "special": "bleed",
     "flavour": "A Godshard fragment is embedded in their sternum. "
                "It was not put there willingly. "
                "The fragment radiates something that makes your own shard pulse uncomfortably."},
    {"name": "Stone Sentinel",
     "hp": 40, "attack": 6, "defence": 14, "tier": 2,
     "gold": (8, 15),
     "loot_chance": 0.6, "loot": "Eldrosian Plate",
     "death_line": "Stops. Exactly where it stood. It does not fall. It simply stops.",
     "special": None,
     "flavour": "Carved from the same stone as the walls. Moves as though it has always moved. "
                "Hits infrequently but with great patience."},
    # Tier 3
    {"name":"Shade of Morvath",     "hp":22,"attack":10,"defence":3,"tier":3,"gold":(0,5),
     "loot_chance":0.7,"loot":"Void Shard",       "death_line":"The shade dissolves. The floor where it stood is grave-cold.","special":"drain"},
    {"name":"Void-Touched Soldier", "hp":28,"attack":9, "defence":4,"tier":3,"gold":(4,11),
     "loot_chance":0.6,"loot":"Eldrosian Plate",  "death_line":"The soldier crumples. The darkness in its eyes fades.",      "special":None},
    {"name":"Blood Crawler",        "hp":20,"attack":8, "defence":2,"tier":3,"gold":(0,4),
     "loot_chance":0.5,"loot":"Blood Amber",      "death_line":"Collapses into itself. A wet red stain.",                    "special":"poison"},
    {"name":"Deep Sentinel",        "hp":32,"attack":11,"defence":5,"tier":3,"gold":(4,14),
     "loot_chance":0.7,"loot":"Ashen Key",        "death_line":"Falls slowly, as though surprised.",                         "special":None},
    {"name":"Hollow Knight",        "hp":25,"attack":9, "defence":6,"tier":3,"gold":(3,10),
     "loot_chance":0.6,"loot":"Warden's Key",     "death_line":"The armour empties. Nothing was inside. Or nothing remains.","special":"fear"},
    {"name":"Void-Touched Cultist",  "hp":24, "attack":9,  "defence":3,  "tier":3, "gold":(1,8), "loot_chance":0.7, "loot":"Cultist's Sigil",
     "death_line": "The cultist falls. Their eyes, even closed, seem to be looking at something you cannot see.", "special":"drain"},
    {"name": "Morvath Shade",
     "hp": 30, "attack": 11, "defence": 4, "tier": 3,
     "gold": (0, 8),
     "loot_chance": 0.7, "loot": "Morvath Eye",
     "death_line": "The darkness it carried is released. The room is briefly, completely black. "
                   "Then ordinary dark.",
     "special": "drain",
     "flavour": "A true Morvath — not corrupted, not summoned. One of the last. "
                "It is here because this is the darkness it chose."},
    {"name": "Flesh Architect",
     "hp": 28, "attack": 10, "defence": 3, "tier": 3,
     "gold": (3, 10),
     "loot_chance": 0.5, "loot": "Blood Amber",
     "death_line": "What it had assembled separates. The pieces are from several different sources.",
     "special": "bleed",
     "flavour": "Builds itself from whatever is in the room. Each round of combat "
                "it becomes slightly harder to hurt, if you let it."},
    {"name": "Void Priest",
     "hp": 26, "attack": 12, "defence": 3, "tier": 3,
     "gold": (6, 14),
     "loot_chance": 0.9, "loot": "Cultist's Sigil",
     "death_line": "Falls mid-chant. The word it was saying is not completed. "
                   "You do not want to know what word.",
     "special": "drain",
     "flavour": "Calls on Atraxis by name. The name has partial effect. "
                "The drain attacks feel intentional in a way other drains do not."},
    {"name": "The Hollow",
     "hp": 32, "attack": 13, "defence": 5, "tier": 3,
     "gold": (0, 0),
     "loot_chance": 0.4, "loot": "Void Shard",
     "death_line": "Nothing. It was nothing. Now it is less.",
     "special": "fear",
     "flavour": "No name. No face. No reason to be here. "
                "It does not attack because it wants to. "
                "It attacks because you are here and it is not nothing."},
    # Tier 4
    {"name":"Unmade Fragment",      "hp":38,"attack":13,"defence":4,"tier":4,"gold":(5,15),
     "loot_chance":0.8,"loot":"Void Shard",       "death_line":"Tears apart silently. The pieces do not stay where they fall.","special":"drain"},
    {"name":"Herald of the Dark",   "hp":30,"attack":12,"defence":6,"tier":4,"gold":(8,20),
     "loot_chance":0.6,"loot":"Agreement Stone",        "death_line":"Speaks one word as it dies. You will not forget it.",         "special":None},
    {"name":"Void-Born Serpent",    "hp":34,"attack":11,"defence":3,"tier":4,"gold":(5,15),
     "loot_chance":0.7,"loot":"Void Shard","death_line":"The serpent stills. The darkness it carried disperses.",       "special":"poison"},
    {"name":"Corrupted High Priest", "hp":50, "attack":16, "defence":7,  "tier":4, "gold":(15,29), "loot_chance":0.9, "loot":"Second Godshard",
     "death_line": "The priest collapses. Something leaks from the wounds that is not blood. The robes continue to move for a moment after the body is still.",
     "special":"drain"},
    {"name":"Atraxis Fragment",      "hp":44, "attack":15, "defence":5,  "tier":4, "gold":(0, 0), "loot_chance":0.5, "loot":"Cultist's Sigil",
     "death_line": "The fragment tears itself apart. The pieces do not fall — they drift, slowly, as though gravity has an opinion about this but is choosing not to enforce it.",
     "special":"drain"},
    {"name": "Keeper's Remnant",
     "hp": 42, "attack": 14, "defence": 6, "tier": 4,
     "gold": (12, 25),
     "loot_chance": 0.8, "loot": "Ashen Tablet",
     "death_line": "Whatever was holding it together releases. "
                   "It falls in stages — first the form, then the will.",
     "special": "drain",
     "flavour": "What is left of a High Keeper who attempted the Agreement and failed — "
                "or succeeded only partially. "
                "It still performs the ritual gestures. It no longer has a mouth to speak the words."},
    {"name": "Atheron's Nightmare",
     "hp": 38, "attack": 15, "defence": 4, "tier": 4,
     "gold": (0, 0),
     "loot_chance": 0.6, "loot": "Dragon Scale",
     "death_line": "Dissolves. It was not real. Nothing from dreams is real when you are awake.",
     "special": "fear",
     "flavour": "This is not Atheron. This is something from Atheron's sleep. "
                "Dragons dream. This is what a sleeping dragon fears."},
    {"name": "Void-Fused Knight",
     "hp": 50, "attack": 16, "defence": 8, "tier": 4,
     "gold": (15, 28),
     "loot_chance": 0.9, "loot": "Voidforged Sword",
     "death_line": "The armour empties and the void within it disperses. "
                   "The metal itself looks relieved.",
     "special": "drain",
     "flavour": "Full plate armour, Eldrosian-made, Void-corrupted. "
                "Whatever was inside the armour originally is gone. "
                "What is there now is not a soldier. It is a direction."},
    # Tier 5
    {"name":"Void Colossus",         "hp":65, "attack":18, "defence":8,  "tier":5, "gold":(20,40), "loot_chance":0.8, "loot":"Void Shard",
     "death_line": "The Colossus unravels from the outside inward — the last thing to go is whatever was at its centre, which turns out to be nothing.",
     "special":"drain"},
    {"name":"Architect's Echo",      "hp":55, "attack":20, "defence":6,  "tier":5, "gold":(15,35), "loot_chance":0.7, "loot":"Echoed Blade",
     "death_line": "The Echo dissolves mid-strike, leaving the impression of a shape in the air that fades over several seconds.",
     "special":"fear"},
    {"name":"Atraxis Tendril",       "hp":48, "attack":16, "defence":10, "tier":5, "gold":(0,0), "loot_chance":0.6, "loot":"Cultist's Sigil",
     "death_line": "The tendril retreats into a crack in the wall. You are not sure it is dead. It is simply elsewhere.",
     "special":"drain"},
    {"name":"The Hollow Warden",     "hp":70, "attack":17, "defence":9,  "tier":5, "gold":(27,47), "loot_chance":0.9, "loot":"Warden's Coat",
     "death_line": "The Warden falls in sections — first the will, then the form. Whatever made it move has gone back where it came from.",
     "special":"fear"},
    {"name": "The Agreement's Witness",
     "hp": 60, "attack": 18, "defence": 7, "tier": 5,
     "gold": (0, 0),
     "loot_chance": 0.7, "loot": "Cultist's Sigil",
     "death_line": "Falls. Has been standing since the Agreement. "
                   "It did not die of anything you did. It died of being finally permitted to.",
     "special": "fear",
     "flavour": "Was present when Maelvyr made the Agreement. Has not left this level since. "
                "It witnessed. Witnessing changed it. It does not speak. "
                "It watches you with the specific attention of something that was there."},

    {"name": "Architect's Hand",
     "hp": 55, "attack": 20, "defence": 6, "tier": 5,
     "gold": (0, 0),
     "loot_chance": 0.5, "loot": "Void Shard",
     "death_line": "Something vast shifts, far away, as if registering the loss of a finger.",
     "special": "drain",
     "flavour": "Not a metaphor. A literal hand, the size of a room, emerging from the Void. "
                "It was not sent. It wandered here. "
                "Hands without bodies reach for things. This one is reaching."},
    {"name": "The Named",
     "hp": 52, "attack": 17, "defence": 9, "tier": 5,
     "gold": (20, 35),
     "loot_chance": 0.9, "loot": "Void Shard",
     "death_line": "Falls. The name they learned is still in them. It will not leave with the body.",
     "special": "drain",
     "flavour": "A cultist who learned Atraxis's true name. The name is partially transforming them. "
                "They are becoming a Demongod — incompletely, agonisingly. "
                "They fight with the desperation of something that cannot decide "
                "whether it wants to finish the process or be stopped."},
    {"name": "The Unmade Shepherd",
     "hp": 68, "attack": 16, "defence": 10, "tier": 5,
     "gold": (25, 40),
     "loot_chance": 0.8, "loot": "Voidhardened Vest",
     "death_line": "The things it was herding scatter. Without direction they are less dangerous. "
                   "They were never the threat. It was.",
     "special": "drain",
     "flavour": "Commands other void creatures. Fights from behind them. "
                "When the Shepherd dies, all remaining void creatures in the room flee. "
                "It is not a commander by choice. It is a commander by nature."},
]